seasons = {
    "2019": {
        "teams": [
            "Milan",
            "Sampdoria",
            "Genoa",
            "Parma",
            "Fiorentina",
            "Lazio",
            "Spal",
            "Lecce",
            "Verona",
            "Juventus",
            "Udinese",
            "Atalanta",
            "Inter",
            "Torino",
            "Cagliari",
            "Bologna",
            "Roma",
            "Brescia",
            "Napoli",
            "Sassuolo",
        ],
        "ongoing": False,
        "days": 38,
    },
    "2020": {
        "teams": [
            "Milan",
            "Sampdoria",
            "Genoa",
            "Parma",
            "Fiorentina",
            "Lazio",
            "Crotone",
            "Spezia",
            "Verona",
            "Juventus",
            "Udinese",
            "Atalanta",
            "Inter",
            "Torino",
            "Cagliari",
            "Bologna",
            "Roma",
            "Benevento",
            "Napoli",
            "Sassuolo",
        ],
        "ongoing": False,
        "days": 38,
    },
    "2021": {
        "teams": [
            "Milan",
            "Sampdoria",
            "Genoa",
            "Venezia",
            "Fiorentina",
            "Lazio",
            "Salernitana",
            "Spezia",
            "Verona",
            "Juventus",
            "Udinese",
            "Atalanta",
            "Inter",
            "Torino",
            "Cagliari",
            "Bologna",
            "Roma",
            "Empoli",
            "Napoli",
            "Sassuolo",
        ],
        "ongoing": False,
        "days": 38,
    },
    "2022": {
        "teams": [
            "Milan",
            "Sampdoria",
            "Lecce",
            "Monza",
            "Fiorentina",
            "Lazio",
            "Salernitana",
            "Spezia",
            "Verona",
            "Juventus",
            "Udinese",
            "Atalanta",
            "Inter",
            "Torino",
            "Cremonese",
            "Bologna",
            "Roma",
            "Empoli",
            "Napoli",
            "Sassuolo",
        ],
        "ongoing": False,
        "days": 38,
    },
    "2023": {
        "teams": [
            "Milan",
            "Frosinone",
            "Lecce",
            "Monza",
            "Fiorentina",
            "Lazio",
            "Salernitana",
            "Genoa",
            "Verona",
            "Juventus",
            "Udinese",
            "Atalanta",
            "Inter",
            "Torino",
            "Cagliari",
            "Bologna",
            "Roma",
            "Empoli",
            "Napoli",
            "Sassuolo",
        ],
        "ongoing": True,
        "days": 37,
    },
}
