#:include layouts/scorepage/utilbar/UtilBar.kv
#:include layouts/scorepage/navigation/PageNavigator.kv
#:include layouts/scorepage/resultbox/ResultBox.kv


<ScorePage>:
    utilbar: utilbar
    navigation: navigation
    resultbox: resultbox
    UtilBar:
        id: utilbar
        pos_hint: {'x': 0.00, 'y': 0.95}
        size_hint: 1.00, 0.05
    PageNavigator:
        id: navigation
    ResultBox:
        id: resultbox