<OneXTwo@FloatLayout>:
    area: "1X2"
    CustomGrid:
        cols: 3
        pos_hint: {"x": 0.05, "y": 0.56}
        size_hint: (0.9, 0.075)
        LabelButton:
            text: "2" 
        LabelButton:
            text: "X" 
        LabelButton:
            text: "1" 
        
    CustomGrid:
        cols: 3
        pos_hint: {"x": 0.05, "y": 0.46}
        size_hint: (0.9, 0.1)
        ProbabilityButton:
        ProbabilityButton:
        ProbabilityButton: